### PR TITLE
Composer improvements

### PR DESCRIPTION
**Pull request by EmanueleMinotto**

### CODE REVIEW

**Comment by EmanueleMinotto** [comment]
@beberlei what do you think about removing `microsoft/windowsazure` and related pear dependencies?
```
  Problem 1
    - The requested package pear-pear2.php.net/http_request2 could not be found in any version, there may be a typo in the package name.
```

**Comment by beberlei** [comment]
@EmanueleMinotto this should work given the composer file sets a new repository to enable PEAR.

**Comment by beberlei** [comment]
@EmanueleMinotto yes please remove, i cant get it to work myself anymore.

**Comment by EmanueleMinotto** [comment]
I'm having this problem even with the PEAR repository included.

```
$ composer install
Loading composer repositories with package information
Initializing PEAR repository http://pear.php.net
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for microsoft/windowsazure dev-master -> satisfiable by microsoft/windowsazure[dev-master].
    - microsoft/windowsazure dev-master requires pear-pear2.php.net/http_request2 * -> no matching package found.
```

**Comment by EmanueleMinotto** [comment]
:+1:

**Comment by EmanueleMinotto** [comment]
@beberlei done, let me know if something else should be done

**Pull request merged**
