### PR TITLE
Mapping drivers

### PR DESCRIPTION
**Pull request by EmanueleMinotto**
Should be a solution (a first draft at least) for #12 and #13

``` xml
<!-- Doctrine.Tests.KeyValueStore.Functional.Post.dcm.xml -->
<?xml version="1.0" encoding="UTF-8"?>
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping
                          http://raw.github.com/doctrine/doctrine2/master/doctrine-mapping.xsd">
	<entity name="Doctrine\Tests\KeyValueStore\Functional\Post" storage-name="post">
		<id>id</id>
	</entity>
</doctrine-mapping>
```

``` yaml
# Doctrine.Tests.KeyValueStore.Functional.Post.dcm.yml
Doctrine\Tests\KeyValueStore\Functional\Post:
  storageName: post
  id:
    - id
  transient:
    - foo
    - bar
```

The identifier can also be a string. A single attribute as identifier should be a common thing (I think).

### CODE REVIEW

**Comment by beberlei** [comment]
Why do you break BC on the Annotations namespaces so drastically? This requires changes to every user for no good reason.

**Comment by beberlei** [comment]
Its not documented in the PR description that you changed the Annotation namespaces as well

**Comment by EmanueleMinotto** [comment]
just tried to align it with the same doctrine2 (before a v1 release), anyway no problem, I'm going to move annotations back to `Doctrine\KeyValueStore\Mapping\Annotations` :+1:

**Comment by EmanueleMinotto** [comment]
@beberlei done, let me know if I should squash the commits

**Comment by beberlei** [comment]
@EmanueleMinotto please move the driver back as well into the `Doctrine\KeyValueStore\Mapping` namespace.

It is not really important to be consistent with ORM here, and it doesn't make a huge difference.

**Pull request merged**
