### PR TITLE
composer: use PSR-4 autoload

### PR DESCRIPTION
**Pull request by TomasVotruba**
PSR-0 is deprecated over a year

### CODE REVIEW

**Comment by EmanueleMinotto** [comment]
Doctrine generally accept PSR-0 only.
They are one of the few FIG members that voted against PSR-4 due to its confusing prefixing/path matching syntax.

**Comment by TomasVotruba** [comment]
Not really:

-  https://github.com/doctrine/migrations/blob/7eb674d75e3d92e86d92c868d8f84fd99095a5ee/composer.json#L27-L36
- https://github.com/doctrine/doctrine2/blob/b1451cda5253f34bf2eca146bbfabd7c6448da1c/composer.json#L33-L38

But I've heard different doctrine repositories are under different maintainers, thus different rules.

Also, since it works, I see no reason not to use it.

**Comment by EmanueleMinotto** [comment]
Well, if so I'm ok with your PR @TomasVotruba :+1:

@Ocramius what do you think about this?

**Comment by beberlei** [comment]
This is fine when it doesnt move the files up to the topmost namespace or just into lib/, so :+1: from me

**Comment by TomasVotruba** [comment]
:+1: Thanks

**Comment by EmanueleMinotto** [comment]
Now I know, thanks @beberlei :)

**Pull request merged**
