### PR TITLE
Fixed wrong instance reference

### PR DESCRIPTION
**Pull request by EmanueleMinotto**

### CODE REVIEW

**Comment by Ocramius** [comment]
@EmanueleMinotto test required.

**Comment by EmanueleMinotto** [comment]
@Ocramius I'm trying to move from current tests (a mix of functional & unit tests, covering a small percentage of the source) to a full coverage with unit tests in the `tests/refactoring` branch (this change is covered here: https://github.com/doctrine/KeyValueStore/commit/f98158d5939f657db1d31adaf9282fb2f0279e13#diff-53f3cbd0c04bbc695439d89d9e894943R252).

Is it ok or not? Should I also add tests here anyway?

**Comment by Ocramius** [comment]
@EmanueleMinotto this particular case can most probably be unit tested

**Comment by EmanueleMinotto** [comment]
Imported a test from the new suite, covers this change too.

**Comment by Ocramius** [comment]
:+1:

**Pull request merged**
